import { MainMenu, MenuList } from '../Models/sidebar-menu-list.model';

export const sidebarMenuLists: MenuList[] = [
  {
    menuId: MainMenu.Info,
    label: 'information',
    imageUrl: '../assets/images/dashboard_icon.svg',
    activeImageUrl: '../assets/images/dashboard_icon.svg',
    alt: 'Home',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Leave,
    label: 'leaves',
    imageUrl: '../assets/images/user.svg',
    activeImageUrl: '../assets/images/user.svg',
    alt: 'onboarding',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Leave,
    label: 'leaves',
    imageUrl: '../assets/images/organization_icon.svg',
    activeImageUrl: '../assets/images/organization_icon.svg',
    alt: 'Home',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.TimeSheet,
    label: 'User',
    imageUrl: '../assets/images/timesheet_icon.svg',
    activeImageUrl: '../assets/images/timesheet_icon.svg',
    alt: 'Home',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Leave,
    label: 'leaves',
    imageUrl: '../assets/images/leavemgmt_icon.svg',
    activeImageUrl: '../assets/images/leavemgmt_icon.svg',
    alt: 'onboarding',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Leave,
    label: 'leaves',
    imageUrl: '../assets/images/goal_icon.svg',
    activeImageUrl: '../assets/images/goal_icon.svg',
    alt: 'Home',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.TimeSheet,
    label: 'User',
    imageUrl: '../assets/images/refer_icon.svg',
    activeImageUrl: '../assets/images/refer_icon.svg',
    alt: 'Home',
    isActive: false,
    subItem: [],
  },
];
