import { MainMenu, MenuList } from '../Models/sidebar-menu-list.model';

export const sidebarMenuLists: MenuList[] = [
  {
    menuId: MainMenu.DAS,
    label: 'DAS',
    imageUrl: '../assets/images/das.svg',
    activeImageUrl: '../assets/images/das-active.svg',
    alt: 'DAS',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.STB,
    label: 'STB',
    imageUrl: '../assets/images/stb.svg',
    activeImageUrl: '../assets/images/stb-active.svg',
    alt: 'STB menu',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.User,
    label: 'User',
    imageUrl: '../assets/images/user.svg',
    activeImageUrl: '../assets/images/user-active.svg',
    alt: 'user',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Customers,
    label: 'Customers',
    imageUrl: '../assets/images/customer.svg',
    activeImageUrl: '../assets/images/customer-active.svg',
    alt: 'customer',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Products,
    label: 'Products',
    imageUrl: '../assets/images/product.svg',
    activeImageUrl: '../assets/images/product-active.svg',
    alt: 'product',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Channels,
    label: 'Channels',
    imageUrl: '../assets/images/channel.svg',
    activeImageUrl: '../assets/images/channel-active.svg',
    alt: 'channels',
    isActive: true,
    subItem: [],
  },
  {
    menuId: MainMenu.Speaker,
    label: 'Speaker',
    imageUrl: '../assets/images/speaker.svg',
    activeImageUrl: '../assets/images/speaker-active.svg',
    alt: 'speaker',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Report,
    label: 'Report',
    imageUrl: '../assets/images/report.svg',
    activeImageUrl: '../assets/images/report-active.svg',
    alt: 'report',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.TRAI,
    label: 'TRAI',
    imageUrl: '../assets/images/trai.svg',
    activeImageUrl: '../assets/images/trai-active.svg',
    alt: 'TRAI',
    isActive: false,
    subItem: [],
  },
  {
    menuId: MainMenu.Settings,
    label: 'Setting',
    imageUrl: '../assets/images/setting.svg',
    activeImageUrl: '../assets/images/setting-active.svg',
    alt: 'setting',
    isActive: false,
    subItem: [],
  },
];
